### ISSUE TITLE
error in new version

### ISSUE THREAD

**Issue by tyjiang1997** [naver/kapture-localization#11]
when I use 'kapture  == 1.1.1 and 'kapture-localization==0.1.2' to run this benchmark mapping code :
`
kapture_pipeline_image_retrieval_benchmark.py -v info \
      -i Aachen-Day-Night-v1.1/mapping \
      --query Aachen-Day-Night-v1.1/query_all \
      -kpt Aachen-Day-Night-v1.1/local_features/r2d2_WASF-N8_20k/keypoints \
      -desc Aachen-Day-Night-v1.1/local_features/r2d2_WASF-N8_20k/descriptors \
      -gfeat Aachen-Day-Night-v1.1/global_features/AP-GeM-LM18/global_features \
      -matches Aachen-Day-Night-v1.1/local_features/r2d2_WASF-N8_20k/NN_no_gv/matches \
      -matches-gv Aachen-Day-Night-v1.1/local_features/r2d2_WASF-N8_20k/NN_colmap_gv/matches \
      --colmap-map Aachen-Day-Night-v1.1/colmap-sfm/r2d2_WASF-N8_20k/frustum_thresh10_far50/colmap \
      -o Aachen-Day-Night-v1.1/image_retrieval_benchmark/r2d2_WASF-N8_20k/frustum_thresh10_far50/AP-GeM-LM18_top20 \
      --topk 20 \
      --config 2
`
I encounter this error:
`ImportError: cannot import name 'guess_feature_name_from_path' from 'kapture.io.features' (/home/jty/anaconda3/envs/vslam/lib/python3.7/site-packages/kapture/io/features.py)`
Is that something wrong with the new version?

**Comment by tyjiang1997** [comment]
hi~ Could you provide this file:
`Aachen-Day-Night-v1.1/colmap-sfm/r2d2_WASF_N8_20k/ir_benchmark/colmap/kapture_inputs/proxy_mapping/reconstruction/keypoints/r2d2_WASF_N8_20k/keypoints.txt`
I think it was here with problem

**Comment by yocabon** [comment]
Hi, are you running kapture-localization's code from the repository source file but have kapture installed through pip ?
I did move the function to the kapture repository very recently, see this commit [guess_feature_name_from_path moved to kapture ](https://github.com/naver/kapture-localization/commit/e54bad2c88be17a83dc55156d6b72b2cf7be6181)

Neither kapture not kapture-localization had a release made since then.
Usually, I work with both kapture and kapture-localization from source. The way to do it is to have both repositories cloned side by side. (In code, it looks for the local version first, see [path_to_kapture.py](https://github.com/naver/kapture-localization/blob/main/kapture_localization/utils/path_to_kapture.py)

**Comment by tyjiang1997** [comment]
Thanks for all your replies. Fianally, I always encounter this question:
  assert kdata.descriptors is not None 
https://github.com/naver/kapture-localization/blob/main/tools/kapture_compute_matches.py#L88
`
no matter the 0.0.4 version or 0.1.2 version.
But I can solve this by move corresponding floders, but after that anotner question comes:
 (sequences/gopro3_undistorted/gopro3_00188.png , sequences/gopro3_undistorted/gopro3_00663.png),
(sequences/gopro3_undistorted/gopro3_00799.png , sequences/gopro3_undistorted/gopro3_00948.png),
(sequences/gopro3_undistorted/gopro3_00480.png , sequences/gopro3_undistorted/gopro3_00514.png),
(sequences/gopro3_undistorted/gopro3_00915.png , sequences/nexus4_sequences/sequence_7/aachen_nexus4_seq7_0148.png),
(db/1855.jpg , db/525.jpg),
(db/1439.jpg , db/1561.jpg),
(db/1755.jpg , sequences/gopro3_undistorted/gopro3_01005.png),
(sequences/gopro3_undistorted/gopro3_00359.png , sequences/gopro3_undistorted/gopro3_00382.png),
(sequences/gopro3_undistorted/gopro3_00878.png , sequences/gopro3_undistorted/gopro3_01011.png),
(db/732.jpg , sequences/nexus4_sequences/sequence_4/aachen_nexus4_seq4_0333.png)
], 'r2d2_WASF-N8_20k': no matches} has more than 1 item, cannot decide which to pick

**Comment by tyjiang1997** [comment]
Could you tell me a stable version of kapture an kapture-location? Thanks, And I also want to do more with your repo
