### ISSUE TITLE
max-scale = 9999 in Aachen example script of R2D2 extraction

### ISSUE THREAD

**Issue by AddASecond** [naver/kapture-localization#16]
in examples of Aachen Day-Night v1.1, the shell script set max-scale to 9999, how does this make sense?

`${PYTHONBIN} extract_kapture.py --model models/r2d2_WASF_N8_big.pt --kapture-root ${WORKING_DIR}/${DATASET}/map_plus_query/ --min-scale 0.3 --min-size 128 --max-scale 9999 --top-k ${KPTS}`
https://github.com/naver/kapture-localization/blob/main/pipeline/examples/run_aachen-v11.sh#L70

but in  kapture/r2d2, max-scale can't > 1:
`assert max_scale <= 1`
https://github.com/naver/r2d2/blob/d6777a9d6769448998e5abe11031ae05de28e49a/extract.py#L61

This will result in an error while running run_aachen-v11.sh

**Comment by yocabon** [comment]
Hi, thanks for the issue, it was meant to be max-size, not max-scale. max-scale do not need to change and stay at 1.
fixed in https://github.com/naver/kapture-localization/commit/a2b3ff49dc257db8a4902f22e1f5ce07d3f3f0f6
