### ISSUE TITLE
Implementation of precision@k and recall@k evaluation

### ISSUE THREAD

**Issue by Barry-Liang** [naver/kapture-localization#21]
Hi, authors. I am impressed by your great work. Thanks a lot for open-sourcing the code and for the detailed toolbox documentation. I am now trying to evaluate some other image retrieval networks using your benchmark. I see the toolbox could evaluate the pose estimation accuracy in local or global sfm as a metric for the image retrieval method. In your paper, you also directly evaluate the recall@k and precision@k of different image retrieval methods on all three datasets. **Is the evaluation function (recall@k precision@k) included in this toolbox?**

**Comment by yocabon** [comment]
Hi,
no the pairs and code used to compute recall@k and precision@k (Figure 2 of Benchmarking Image Retrieval for Visual Localization for example) is not part of kapture-localization.
