### ISSUE TITLE
No trajectory.txt for the query images in RobotCar and Aachen Datasets

### ISSUE THREAD

**Issue by Barry-Liang** [naver/kapture-localization#24]
Hi, authors. I am now trying to evaluate the performance of my image retrieval network. But I found no trajectory.txt for the query images in RobotCar and Aachen Dataset. However, the ground truth poses information is necessary for the final accuracy evaluation. (at least not included in your dataset downloader). I will appreciate it if you can provide the files.

Thanks in advance!

**Comment by yocabon** [comment]
Hi,
query ground truth poses are not publicly available for aachen and robotcar. To evaluate them, you have to submit the localization result (in a different format) to https://www.visuallocalization.net/ 

About format:
There is a script in kapture to export a kapture folder to the format expected by visuallocalization.net (note that the format changes depending on the dataset) -> https://github.com/naver/kapture/blob/main/tools/kapture_export_LTVL2020.py

the pipeline scripts in kapture-localization should already do this export https://github.com/naver/kapture-localization/tree/main/pipeline (once finished, there should be a file "[something]_LTVL2020_style.txt" that can be submitted to the website.
