### ISSUE TITLE
RGBD pipeline

### ISSUE THREAD

**Issue by Mukulareddy** [naver/kapture-localization#25]
Hello,
I would want to test kapture RGBD pipeline. But i couldn't find any implementation details as mentioned in the research paper. Can someone help me with this.

Thanks
Mukula

**Comment by humenbergerm** [comment]
Hi!

Right now, we do not have a complete, ready to use RGBD pipeline in place. However, you can use this script to construct the map from an RGBD dataset: tools/kapture_create_3D_model_from_depth.py

I will add a pipeline example as soon as I can.

Best,
Martin
