### ISSUE TITLE
Pose estimation

### ISSUE THREAD

**Issue by Zumbalamambo** [naver/kapture-localization#3]
The structure of the code is not clear. May I know how the pose is estimated in localization?

**Comment by humenbergerm** [comment]
Hi!

Please see the [tutorial](https://github.com/naver/kapture-localization/blob/master/doc/tutorial.adoc) for more information about the localization methods (algorithms, references, code examples) we use.
In short, we use an image retrieval, structure-based method, and COLMAP for SFM (point triangulation from known poses) and pose estimation from 2D-3D matches (PNP).

Does this help?

Best,
Martin
