### ISSUE TITLE
Get much lower global_sfm results for OpenIBL

### ISSUE THREAD

**Issue by shuimushan** [naver/kapture-localization#41]
I directly downloaded the model_best.pth.tar and pca_params_model_best.h5 for sfrs from the google drive link offered by the author of OpenIBL. And produce global features like [extract_kapture.py](https://github.com/naver/r2d2/blob/master/extract_kapture.py) with pca whitening. Then I ran kapture_pipeline_image_retrieval_benchmark.py and get sfrs_top1(Feather2d2 20k) results for global_sfm:

Model: global_sfm_config_2

Found 688 / 916 image positions (75.11 %).
Found 688 / 916 image rotations (75.11 %).
Localized images: mean=(38.5954m, 50.3685 deg) / median=(10.5967m, 2.3077 deg)
All: median=(39.9641m, 24.5639 deg)
Min: 0.0037m; 0.0890 deg
Max: 1678.3912m; 179.9506 deg

(0.25m, 2.0 deg): 30.79%
(0.5m, 5.0 deg): 33.41%
(5.0m, 10.0 deg): 34.61%

which is much lower than the results you offered for openibl_vgg16_netvlad:
(0.25m_2.0deg):42.36%
(1.0m_5.0deg):48.03%
median distance (m):10.6814
median angle (deg):1.8746

What may be the problems I get while reproducing the results?

I also use the openibl_vgg16_netvlad global features provided by you and get similar results as the benchmark:

Model: global_sfm_config_2

Found 789 / 916 image positions (86.14 %).
Found 789 / 916 image rotations (86.14 %).
Localized images: mean=(31.5377m, 38.1892 deg) / median=(0.1040m, 1.4645 deg)
All: median=(10.0326m, 1.9461 deg)
Min: 0.0037m; 0.1103 deg
Max: 197.0356m; 179.9974 deg

(0.25m, 2.0 deg): 42.03%
(0.5m, 5.0 deg): 47.60%
(5.0m, 10.0 deg): 48.47%

**Comment by yocabon** [comment]
I don't know. What I can tell you is that to extract global features for openibl, we (minus some pipelining difference) followed the quickstart guide https://github.com/yxgeee/OpenIBL#extract-descriptor-for-a-single-image
