### ISSUE TITLE
About the pretrained checkpoint for r2d2 local features used on the benchmark

### ISSUE THREAD

**Issue by shuimushan** [naver/kapture-localization#42]
I wonder what the checkpoint file is for feather2d2_dim32_20k as well as the file for r2d2_WASF-N8_20k. Are there any download links for them?

**Comment by yocabon** [comment]
Hi, the checkpoint for feather2d2 is not public. The other one is available in the r2d2 repository https://github.com/naver/r2d2/blob/master/models%2Fr2d2_WASF_N8_big.pt

**Comment by shuimushan** [comment]
Thanks!
