### ISSUE TITLE
Parameters for global descriptor extraction

### ISSUE THREAD

**Issue by Skydes** [naver/kapture-localization#5]
Hi there,

I am writing regarding your 3DV paper "Benchmarking Image Retrieval for Visual Localization". Really cool paper with many insights! Thanks a lot for open-sourcing the code and for the extensive documentation.

I am looking for the pre- and post-processing parameters used to extract the global descriptors such as NetVLAD, AP-GeM, and DELG. I am particularly interested in the size of the input images, the exact scales (if multiscale extraction), whether whitening was applied, etc. I could not find such details in the paper and this repository does not seem to mention the arguments of the extraction scripts (e.g. [extract_kapture.py](https://github.com/naver/deep-image-retrieval/blob/master/dirtorch/extract_kapture.py) for AP-GeM). These would be very useful to reproduce the benchmark results and compare them with other datasets.

Thanks a lot!

**Comment by humenbergerm** [comment]
Hi Paul-Edouard!

Thanks for your interest in our benchmark. Sorry if we missed some implementation details in the paper or the suppl. mat. Let me summarize this here.

If not indicated differently, we used the default parameters of the scripts. We also provided the unchanged dataset images to the feature extractors.
- DenseVLAD: Code available at http://www.ok.ctrl.titech.ac.jp/~torii/project/247/. For the multi-scale variant, we used 4 different scales corresponding to region widths of 16, 24, 32 and 40 pixels.
- DELG: We used this repo [snapshot](https://github.com/tensorflow/models/tree/afdf2599b37a199821772f0d6eea9d9300cf9f8d/research/delf/delf/python/delg). In the meantime, the DELG code changed a bit. Furthermore, the authors of DELG released more models.
- AP-GeM: We used this script with default params: https://github.com/naver/deep-image-retrieval/blob/master/dirtorch/extract_kapture.py
- NetVLAD: https://github.com/Relja/netvlad

Note that we provide all extracted features in the kapture dataset downloader as well. Please find a detailed tutorial of how to reproduce the results using the provided features [here](https://github.com/naver/kapture-localization/blob/master/doc/benchmark.adoc).

I hope this helps and please let us know if something is unclear.

Best,
Martin

**Comment by Skydes** [comment]
Hi Martin,

Thank you for the swift reply! I thought that multiscale inference was used for AP-GeM (since it usually improves the results) and thus thought that some parameters were missing. I was wrong and the paper indeed includes all the necessary details. Thank you for clarifying.
