### ISSUE TITLE
Unsupported copy action link_absolute

### ISSUE THREAD

**Issue by ChengFengGu** [naver/kapture-localization#6]
Dear author:

While recode the custom localization pipeline using jupyter, 

``` python
merged_kapture = merge_remap(
        kapture_data_list, skip_list, kapture_path_list, merged_path, images_import_strategy)

```

there has a error:

Unsupported copy action link_absolute

![image](https://user-images.githubusercontent.com/39356188/104080741-db09ec80-5264-11eb-8113-14e1e8b75ccf.png)

**Comment by yocabon** [comment]
Hi,
From the error, I think you have a type error.
images_import_strategy should be a TransferAction but I believe you are sending a string instead.

in merge_remap, make sure you have images_import_strategy=TransferAction.link_absolute and not images_import_strategy="link_absolute".
